(lang dune 2.9)
(name reader)

(generate_opam_files true)

(package
 (name reader)
 (depends
   (cohttp-lwt-unix (>= 4.0.0))
   (cohttp-async (>= 4.0.0))
   (yojson (>= 1.7.0))
   (ppx_deriving_yojson (>= 3.6.1))
   (uuidm (>= 0.9.7))
   (safepass (>= 3.1))
   (jose (>= 0.6.0))))
